name = "device-gateway"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[durable_objects]
bindings = [
  { name = "DEVICE_GATEWAY", class_name = "DeviceGatewayDO" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DeviceGatewayDO"]

# Secrets (injected via `wrangler secret put`):
# - SERVICE_TOKEN: Vercel → CF service-to-service auth secret

[vars]
JWKS_PUBLIC_KEY = '{"keys":[{"kty":"RSA","n":"xfIVh_IBF0NQXSyb7M8HBtNeP_yH6fj1C2q2DLSRY9-VYYH6Q_EAGCn1A-rBVSzT2ydwftd5vEByFkCeykNj1UvpbJ2HZG_NwwY1Y9BVYnHyAE4bF43A-d2XsOywPHDRChS1r5Y0y1RqFMpU99efQA3xJkIglSkyzDuVA1LNu8KWyJ7pSRWwJAQc3JxitnMAzmi8rtL0qM1DPDSXrjcjnDhJ8gJB8XYmsOF_0Jz0cbKC29q8tnvIV4uaJWliz8_B-Rch1mgcULYLHXU2mRAITSRL1uE1xDexp1af-qraIaAqbSGodVFE_0jDqF6nFIBFMlxoglZ7aLNVPyRK0rx2zQ","e":"AQAB","alg":"RS256","kid":"1b41c51a75c49287","use":"sig"}]}'
SERVICE_TOKEN = "f12d9a86ed772b66dc343cd67950dcd255a880b324df61d93e12b24b4ad268c2"